name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Setup environment
        run: |
          npm ci
          npm run clean
      - name: Lint source
        run: npm run lint
      - name: Test source
        id: test
        continue-on-error: true
        run: npm run test
      - name: Create test badges
        run: |
          npm run badges
          git add -f report coverage
      - name: Generate dist and build
        if: steps.test.outcome == 'success'
        run: |
          npm run gen
          git add -f dist deno_dist build es_build doc
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f
