name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Setup
        run: |
          npm ci
          npm run clean
      - name: Lint
        run: npm run lint
      - name: Test
        id: test
        continue-on-error: true
        run: npm run coverage
      - name: Generate badges and, add report and coverage
        run: |
          npm run badges
          git add -f report coverage
      - name: Build and doc
        if: steps.test.outcome == 'success'
        run: |
          npm run build
          npm run doc
          git add -f build deno_build doc
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f
