name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup
        run: yarn ci && yarn clean
      - name: Lint
        run: yarn lint
      - name: Test
        id: test
        continue-on-error: true
        run: yarn test
      - name: Performance
        run: |
          yarn perf
      - name: Create badges and add docs
        run: |
          yarn badges
          git add -f docs
      - name: Build and docs
        if: steps.test.outcome == 'success'
        run: |
          yarn build_and_docs
          git add -f dist deno_dist build docs
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f
