name: pr

on:
  pull_request:
    branches: [main]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Setup
        run: npm ci && npm run clean
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage
      - name: Build
        run: npm run build
